name: continuous-integration

on:
  push:

env:
  testing-file: https://raw.githubusercontent.com/nushell/nushell/6a759abcbd9bdc6fb4bbd60144e309bd1a79786b/crates/nu-std/testing.nu

jobs:
  test-node:
    name: test-node (${{ matrix.plugin }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - nu_plugin_node_example

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
      - uses: hustcer/setup-nu@v3
        with:
          version: nightly

      # - name: Download testing.nu
      #   run: wget ${{ env.testing-file }}

      - name: Ensure plugin is executable
        run: chmod +x ./javascript/${{ matrix.plugin }}/${{ matrix.plugin }}.js

      - name: Run tests
        run: nu -c 'use testing.nu; testing run-tests --path ./javascript/${{ matrix.plugin }} --plugins ["./javascript/${{ matrix.plugin }}/${{ matrix.plugin}}.js"]'


  test-python:
    name: test-python (${{ matrix.plugin }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - nu_plugin_python_example
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version" 
      - uses: hustcer/setup-nu@v3
        with:
          version: nightly

      # - name: Download testing.nu
      #   run: wget ${{ env.testing-file }}

      - name: Ensure plugin is executable
        run: chmod +x ./python/${{ matrix.plugin }}/${{ matrix.plugin }}.py

      - name: Run tests
        run: nu -c 'use testing.nu; testing run-tests --path ./python/${{ matrix.plugin }} --plugins ["./python/${{ matrix.plugin }}/${{ matrix.plugin}}.py"]'
      